(function(C,D){function r(a,b){function c(){}c.prototype=a;var f=new c,p;for(p in b)f[p]=b[p];b.toString!==Object.prototype.toString&&(f.toString=b.toString);return f}function E(a){return a instanceof Array?function(){return g.iter(a)}:"function"==typeof a.iterator?l(a,a.iterator):a.iterator}function l(a,b){if(null==b)return null;null==b.__id__&&(b.__id__=F++);var c;null==a.hx__closures__?a.hx__closures__={}:c=a.hx__closures__[b.__id__];null==c&&(c=function(){return c.method.apply(c.scope,arguments)},
c.scope=a,c.method=b,a.hx__closures__[b.__id__]=c);return c}var d=C.AudioPlayer=function(a){var b=this;this.file=new G(a.path);this.wheelSpeed=1;var c=window.getComputedStyle(atom.views.getView(atom.workspace));this.element=window.document.createElement("div");this.element.classList.add("audioplayer");this.element.setAttribute("tabindex","-1");this.waveform=new t(c.color,c.backgroundColor);this.element.appendChild(this.waveform.canvas);this.marker=window.document.createElement("div");this.marker.classList.add("marker");
this.element.appendChild(this.marker);this.audio=window.document.createElement("audio");this.audio.autoplay=a.play;this.audio.controls=!0;this.audio.src=this.file.getPath();this.audio.currentTime=a.time;this.element.appendChild(this.audio);this.element.addEventListener("DOMNodeInserted",function(){b.audio.addEventListener("playing",l(b,b.handleAudioPlaying),!1);b.audio.addEventListener("ended",l(b,b.handleAudioEnded),!1);b.audio.addEventListener("error",l(b,b.handleAudioError),!1);b.audio.addEventListener("canplaythrough",
function(a){b.waveform.color=c.color;b.waveform.canvas.style.backgroundColor=c.backgroundColor;b.waveform.generate(b.file.getPath(),null,function(){b.updateMarker()});b.element.addEventListener("click",l(b,b.handleMouseDown),!1);b.element.addEventListener("mousewheel",l(b,b.handleMouseWheel),!1)},!1)},!1)};d.__name__=["AudioPlayer"];d.activate=function(a){d.context=new AudioContext;d.disposables=new H;d.disposables.add(atom.workspace.addOpener(d.openURI))};d.deactivate=function(){d.disposables.dispose()};
d.openURI=function(a){var b=h.extension(a).toLowerCase();return w.has(d.allowedFileTypes,b)?new d({path:a,play:atom.config.get("audioplayer.autoplay"),time:null}):null};d.consumeStatusBar=function(a){};d.deserialize=function(a){return new d(a)};d.prototype={serialize:function(){return{deserializer:"AudioPlayer",path:this.file.getPath(),play:!this.audio.paused,time:this.audio.currentTime}},dispose:function(){this.audio.pause();this.audio.remove();this.audio=null},getPath:function(){return this.file.getPath()},
getTitle:function(){return this.file.getBaseName()},getURI:function(){var a=this.file.getPath();return"file://"+encodeURIComponent(a)},isEqual:function(a){return e.__instanceof(a,d)?this.getURI()==e.__cast(a,d).getURI():!1},update:function(a){this.animationFrameId=window.requestAnimationFrame(l(this,this.update));this.updateMarker()},seek:function(a){null!=this.audio.currentTime&&(this.audio.currentTime+=a);return this.audio.currentTime},setAudioPositionFromPanePosition:function(a){this.audio.currentTime=
a/this.element.offsetWidth*this.audio.duration},updateMarker:function(){this.marker.style.left=this.audio.currentTime/this.audio.duration*this.element.offsetWidth+"px"},handleAudioPlaying:function(a){this.animationFrameId=window.requestAnimationFrame(l(this,this.update))},handleAudioEnded:function(a){},handleAudioError:function(a){},handleMouseDown:function(a){this.setAudioPositionFromPanePosition(a.layerX)},handleMouseUp:function(a){},handleMouseOut:function(a){},handleMouseWheel:function(a){var b=
a.wheelDelta/100*this.wheelSpeed;a.ctrlKey&&(b*=10,a.shiftKey&&(b*=10));this.seek(b)},handleResize:function(a){this.waveform.resize()},__class__:d};var g=function(){};g.__name__=["HxOverrides"];g.substr=function(a,b,c){if(null==c)c=a.length;else if(0>c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};g.iter=function(a){return{cur:0,arr:a,hasNext:function(){return this.cur<this.arr.length},next:function(){return this.arr[this.cur++]}}};var w=function(){};w.__name__=["Lambda"];w.has=function(a,
b){for(var c=E(a)();c.hasNext();)if(c.next()==b)return!0;return!1};Math.__name__=["Math"];var u=function(){};u.__name__=["Std"];u.string=function(a){return e.__string_rec(a,"")};var x=function(){};x.__name__=["Type"];x.getClassName=function(a){a=a.__name__;return null==a?null:a.join(".")};var t=function(a,b){this.canvas=window.document.createElement("canvas");this.canvas.classList.add("waveform");this.canvas.width=window.innerWidth;this.canvas.height=window.innerHeight;this.color=a;this.canvas.style.backgroundColor=
b;this.context=this.canvas.getContext("2d",null);this.context.fillStyle=a};t.__name__=["Waveform"];t.prototype={generate:function(a,b,c){var f=this;null==b&&(b=window.innerWidth);m.load(d.context,a,function(a,e){null!=a?atom.notifications.addError("Failed to analyze sound data"):(f.peaks=y.getMergedPeaks(e,b),f.draw(f.peaks),null!=c&&c())})},resize:function(){this.canvas.width=window.innerWidth;this.canvas.height=window.innerHeight;this.draw(this.peaks)},draw:function(a){this.context.clearRect(0,
0,this.canvas.width,this.canvas.height);this.context.fillStyle=this.color;for(var b=this.canvas.width/a.length,c=0,f=this.canvas.height/2,e=0;e<a.length;){var d=a[e];++e;this.context.fillRect(c*b,f,b,d*f/2);++c}},__class__:t};var H=require("atom").CompositeDisposable,G=require("atom").File,h=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var b=a.lastIndexOf("/"),c=a.lastIndexOf("\\");b<c?(this.dir=g.substr(a,0,c),a=g.substr(a,c+1,null),this.backslash=!0):c<b?(this.dir=g.substr(a,
0,b),a=g.substr(a,b+1,null)):this.dir=null;b=a.lastIndexOf(".");-1!=b?(this.ext=g.substr(a,b+1,null),this.file=g.substr(a,0,b)):(this.ext=null,this.file=a)};h.__name__=["haxe","io","Path"];h.extension=function(a){a=new h(a);return null==a.ext?"":a.ext};h.prototype={__class__:h};var k=function(a){Error.call(this);this.val=a;this.message=String(a);Error.captureStackTrace&&Error.captureStackTrace(this,k)};k.__name__=["js","_Boot","HaxeError"];k.wrap=function(a){return a instanceof Error?a:new k(a)};
k.__super__=Error;k.prototype=r(Error.prototype,{__class__:k});var e=function(){};e.__name__=["js","Boot"];e.getClass=function(a){if(a instanceof Array&&null==a.__enum__)return Array;var b=a.__class__;if(null!=b)return b;a=e.__nativeClassName(a);return null!=a?e.__resolveNativeClass(a):null};e.__string_rec=function(a,b){if(null==a)return"null";if(5<=b.length)return"<...>";var c=typeof a;"function"==c&&(a.__name__||a.__ename__)&&(c="object");switch(c){case "function":return"<function>";case "object":if(a instanceof
Array){if(a.__enum__){if(2==a.length)return a[0];c=a[0]+"(";b+="\t";for(var f=2,p=a.length;f<p;)var d=f++,c=2!=d?c+(","+e.__string_rec(a[d],b)):c+e.__string_rec(a[d],b);return c+")"}c=a.length;f="[";b+="\t";for(p=0;p<c;)d=p++,f+=(0<d?",":"")+e.__string_rec(a[d],b);return f+"]"}try{f=a.toString}catch(g){return"???"}if(null!=f&&f!=Object.toString&&"function"==typeof f&&(c=a.toString(),"[object Object]"!=c))return c;c=null;f="{\n";b+="\t";p=null!=a.hasOwnProperty;for(c in a)p&&!a.hasOwnProperty(c)||
"prototype"==c||"__class__"==c||"__super__"==c||"__interfaces__"==c||"__properties__"==c||(2!=f.length&&(f+=", \n"),f+=b+c+" : "+e.__string_rec(a[c],b));b=b.substring(1);return f+("\n"+b+"}");case "string":return a;default:return String(a)}};e.__interfLoop=function(a,b){if(null==a)return!1;if(a==b)return!0;var c=a.__interfaces__;if(null!=c)for(var f=0,d=c.length;f<d;){var z=c[f++];if(z==b||e.__interfLoop(z,b))return!0}return e.__interfLoop(a.__super__,b)};e.__instanceof=function(a,b){if(null==b)return!1;
switch(b){case Array:return a instanceof Array?null==a.__enum__:!1;case A:return"boolean"==typeof a;case I:return!0;case B:return"number"==typeof a;case J:return"number"==typeof a?(a|0)===a:!1;case String:return"string"==typeof a;default:if(null!=a)if("function"==typeof b){if(a instanceof b||e.__interfLoop(e.getClass(a),b))return!0}else{if("object"==typeof b&&e.__isNativeObj(b)&&a instanceof b)return!0}else return!1;return b==K&&null!=a.__name__||b==L&&null!=a.__ename__?!0:a.__enum__==b}};e.__cast=
function(a,b){if(e.__instanceof(a,b))return a;throw new k("Cannot cast "+u.string(a)+" to "+u.string(b));};e.__nativeClassName=function(a){a=e.__toStr.call(a).slice(8,-1);return"Object"==a||"Function"==a||"Math"==a||"JSON"==a?null:a};e.__isNativeObj=function(a){return null!=e.__nativeClassName(a)};e.__resolveNativeClass=function(a){return D[a]};require("buffer");var n=function(a,b){Error.call(this,a);this.message=a;this.pos=b;var c=x.getClassName(e.getClass(this));-1!=c.indexOf(".")&&(c=c.split(".").pop());
this.name=c};n.__name__=["om","Error"];n.__super__=Error;n.prototype=r(Error.prototype,{__class__:n});var m=function(){};m.__name__=["om","audio","AudioBufferLoader"];m.load=function(a,b,c){m.loadArrayBuffer(a,b,function(b,e){null!=b?c(b,null):a.decodeAudioData(e,function(a){c(null,a)})})};m.loadArrayBuffer=function(a,b,c){var e=!1,d=new XMLHttpRequest;d.open("GET",b,!0);d.responseType="arraybuffer";d.onreadystatechange=function(a){200==d.status||e||(e=!0,c(new v(b,{fileName:"AudioBufferLoader.hx",
lineNumber:37,className:"om.audio.AudioBufferLoader",methodName:"loadArrayBuffer"}),null))};d.onload=function(a){c(null,d.response)};d.send()};var y=function(){};y.__name__=["om","audio","PeakMeter"];y.getMergedPeaks=function(a,b){for(var c=a.length/b|0,d=~~(c/10|0)|0,e=a.numberOfChannels,g=[],l=0;l<e;)for(var k=l++,n=a.getChannelData(k),q=0;q<b;){for(var h=q++,m=~~(h*c)|0,v=~~(m+c),r=n[0],t=n[0];m<v;){var u=n[m];u>t&&(t=u);u<r&&(r=u);m+=d}if(0==k||t>g[2*h])g[2*h]=t;if(0==k||r<g[2*h+1])g[2*h+1]=r}return g};
var q=function(a,b){n.call(this,""+a+" not found",b);this.location=a};q.__name__=["om","error","NotFound"];q.__super__=n;q.prototype=r(n.prototype,{__class__:q});var v=function(a,b){q.call(this,a,b)};v.__name__=["om","error","FileNotFound"];v.__super__=q;v.prototype=r(q.prototype,{__class__:v});var F=0;module.exports=d;String.prototype.__class__=String;String.__name__=["String"];Array.__name__=["Array"];var J={__name__:["Int"]},I={__name__:["Dynamic"]},B=Number;B.__name__=["Float"];var A=Boolean;
A.__ename__=["Bool"];var K={__name__:["Class"]},L={};d.allowedFileTypes=["aiff","flac","mp3","ogg","wav"];e.__toStr={}.toString})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this,"undefined"!=typeof window?window:"undefined"!=typeof global?global:"undefined"!=typeof self?self:this);
