var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var c=a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,c,d,f){if(c){d=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var e=a[f];e in d||(d[e]={});d=d[e]}a=a[a.length-1];f=d[a];c=c(f);c!=f&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function d(b){return b instanceof e?b:new e(function(g,a){g(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};c.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var f=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(b){f(b,
0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var g=0;g<b.length;++g){var a=b[g];delete b[g];try{a()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};c.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var e=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var g=this.createResolveAndReject_();try{b(g.resolve,g.reject)}catch(k){g.reject(k)}};e.prototype.createResolveAndReject_=
function(){function b(b){return function(d){a||(a=!0,b.call(g,d))}}var g=this,a=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};e.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof e)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};e.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(k){this.reject_(k);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};e.prototype.reject_=function(b){this.settle_(2,b)};e.prototype.fulfill_=function(b){this.settle_(1,b)};e.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a|"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
this.onSettledCallbacks_,a=0;a<b.length;++a)b[a].call(),b[a]=null;this.onSettledCallbacks_=null}};var n=new c;e.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};e.prototype.settleSameAsThenable_=function(a,d){var b=this.createResolveAndReject_();try{a.call(d,b.resolve,b.reject)}catch(m){b.reject(m)}};e.prototype.then=function(a,d){function b(a,b){return"function"==typeof a?function(h){try{c(a(h))}catch(x){g(x)}}:b}var c,g,f=new e(function(a,
b){c=a;g=b});this.callWhenSettled_(b(a,c),b(d,g));return f};e.prototype.catch=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,d){function b(){switch(c.state_){case 1:a(c.result_);break;case 2:d(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?n.asyncExecute(b):this.onSettledCallbacks_.push(function(){n.asyncExecute(b)})};e.resolve=d;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,
c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=e.next())d(f.value).callWhenSettled_(b,c)})};e.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d([]):new e(function(a,e){function f(h){return function(b){g[h]=b;k--;0==k&&a(g)}}var g=[],k=0;do g.push(void 0),k++,d(c.value).callWhenSettled_(f(g.length-1),e),c=b.next();while(!c.done)})};return e},"es6","es3");
(function(a){function c(h,a){if(null==a)return null;null==a.__id__&&(a.__id__=w++);var b;null==h.hx__closures__?h.hx__closures__={}:b=h.hx__closures__[a.__id__];null==b&&(b=function(){return b.method.apply(b.scope,arguments)},b.scope=h,b.method=a,h.hx__closures__[a.__id__]=b);return b}var d=a.AudioPlayer=function(a){var h=this;this.file=new g(a.path,!1);this.isPlaying=!1;this.wheelSpeed=this.seekSpeed=1;var e=window.getComputedStyle(atom.views.getView(atom.workspace));this.element=window.document.createElement("div");
this.element.classList.add("audioplayer");this.element.setAttribute("tabindex","-1");this.spectrum=new n(e.color,e.backgroundColor);this.element.appendChild(this.spectrum.element);this.marker=window.document.createElement("div");this.marker.classList.add("marker");this.element.appendChild(this.marker);this.audio=window.document.createElement("audio");this.audio.controls=!0;this.audio.src=this.file.getPath();this.audio.currentTime=a.time;this.element.appendChild(this.audio);this.audio.addEventListener("playing",
c(this,this.handleAudioPlaying),!1);this.audio.addEventListener("ended",c(this,this.handleAudioEnded),!1);this.audio.addEventListener("error",c(this,this.handleAudioError),!1);this.audio.addEventListener("canplaythrough",c(this,this.handleCanPlayThrough),!1);this.frequencyAnalyser=d.context.createAnalyser();this.frequencyAnalyser.fftSize=128;this.timedomainAnalyser=d.context.createAnalyser();this.timedomainAnalyser.fftSize=2048;this.timedomainAnalyser.connect(this.frequencyAnalyser);this.frequencyData=
new Uint8Array(this.frequencyAnalyser.frequencyBinCount);this.timedomainData=new Float32Array(this.timedomainAnalyser.frequencyBinCount);this.commands=new b;this.commands.add(atom.commands.add(this.element,"audioplayer:toggle-playback",function(a){h.isPlaying?h.pause():h.play()}));this.commands.add(atom.commands.add(this.element,"audioplayer:toggle-mute",function(a){h.audio.muted=!h.audio.muted}));this.commands.add(atom.commands.add(this.element,"audioplayer:seek-backward",function(a){h.seek(-(h.audio.duration/
10*h.seekSpeed))}));this.commands.add(atom.commands.add(this.element,"audioplayer:seek-forward",function(a){h.seek(h.audio.duration/10*h.seekSpeed)}));this.element.addEventListener("click",c(this,this.handleMouseDown),!1);this.element.addEventListener("mousewheel",c(this,this.handleMouseWheel),!1);null!=a.play&&this.play()};d.activate=function(a){d.disposables=new b;d.disposables.add(atom.workspace.addOpener(d.openURI))};d.deactivate=function(){d.disposables.dispose();null!=d.context&&d.context.close()};
d.openURI=function(a){var h=k.extension(a).toLowerCase();return e.has(d.allowedFileTypes,h)?(null==d.context&&(d.context=new AudioContext),new d({path:a,play:atom.config.get("audioplayer.autoplay"),time:null})):null};d.consumeStatusBar=function(a){};d.deserialize=function(a){null==d.context&&(d.context=new AudioContext);return new d(a)};d.prototype={serialize:function(){return{deserializer:"AudioPlayer",path:this.file.getPath(),play:!this.audio.paused,time:this.audio.currentTime}},dispose:function(){this.commands.dispose();
this.element.removeEventListener("click",c(this,this.handleMouseDown));this.element.removeEventListener("mousewheel",c(this,this.handleMouseWheel));this.audio.removeEventListener("playing",c(this,this.handleAudioPlaying));this.audio.removeEventListener("ended",c(this,this.handleAudioEnded));this.audio.removeEventListener("error",c(this,this.handleAudioError));this.audio.pause();this.audio.remove();this.audio=null},getPath:function(){return this.file.getPath()},getTitle:function(){return this.file.getBaseName()},
getURI:function(){var a=this.file.getPath();return"file://"+encodeURIComponent(a)},play:function(){this.isPlaying||(this.isPlaying=!0,this.audio.play())},pause:function(){this.isPlaying&&(this.isPlaying=!1,this.audio.pause())},seek:function(a){null!=this.audio.currentTime&&(this.audio.currentTime+=a);return this.audio.currentTime},setAudioPositionFromPanePosition:function(a){this.audio.currentTime=a/this.element.offsetWidth*this.audio.duration},updateMarker:function(){this.marker.style.left=(this.audio.currentTime/
this.audio.duration*this.element.offsetWidth|0)+"px"},update:function(a){this.animationFrameId=window.requestAnimationFrame(c(this,this.update));this.updateMarker()},togglePlayback:function(){this.isPlaying?this.pause():this.play()},toggleMute:function(){this.audio.muted=!this.audio.muted},handleCanPlayThrough:function(a){this.audio.removeEventListener("canplaythrough",c(this,this.handleCanPlayThrough));this.spectrum.generateWaveForm(this.file.getPath())},handleAudioPlaying:function(a){this.animationFrameId=
window.requestAnimationFrame(c(this,this.update))},handleAudioEnded:function(a){window.cancelAnimationFrame(this.animationFrameId);this.animationFrameId=null},handleAudioError:function(a){},handleMouseDown:function(a){this.setAudioPositionFromPanePosition(a.layerX)},handleMouseUp:function(a){},handleMouseOut:function(a){},handleMouseWheel:function(a){var b=a.wheelDelta/100*this.wheelSpeed;a.ctrlKey&&(b*=10,a.shiftKey&&(b*=10));this.seek(b)},handleResize:function(a){}};var f=function(){};f.substr=
function(a,b,c){if(null==c)c=a.length;else if(0>c)if(0==b)c=a.length+c;else return"";return a.substr(b,c)};f.iter=function(a){return{cur:0,arr:a,hasNext:function(){return this.cur<this.arr.length},next:function(){return this.arr[this.cur++]}}};var e=function(){};e.has=function(a,b){a=a instanceof Array?f.iter(a):a.iterator();for(;a.hasNext();)if(a.next()==b)return!0;return!1};var n=function(a,b){this.element=window.document.createElement("div");this.element.classList.add("spectrum");this.canvasWaveform=
window.document.createElement("canvas");this.canvasWaveform.classList.add("waveform");this.canvasWaveform.width=window.innerWidth;this.canvasWaveform.height=window.innerHeight;this.element.appendChild(this.canvasWaveform);this.canvasFrequency=window.document.createElement("canvas");this.canvasFrequency.classList.add("frequency");this.canvasFrequency.width=window.innerWidth;this.canvasFrequency.height=window.innerHeight;this.element.appendChild(this.canvasFrequency);this.color=a;this.element.style.backgroundColor=
b};n.prototype={generateWaveForm:function(a,b){var c=this;null==b&&(b=window.innerWidth);l.loadAudioBuffer(d.context,a).then(function(a){c.waveform=v.getMergedPeaks(a,b);c.drawWaveform()})},drawWaveform:function(){var a=this.canvasWaveform.getContext("2d",null);a.clearRect(0,0,this.canvasWaveform.width,this.canvasWaveform.height);a.fillStyle=this.color;for(var b=this.canvasWaveform.width/this.waveform.length,c=0,d=this.canvasWaveform.height/2,e=0,f=this.waveform;e<f.length;){var g=f[e];++e;a.fillRect(c*
b,d,b,g*d/2);++c}}};var b=require("atom").CompositeDisposable,g=require("atom").File,k=function(a){switch(a){case ".":case "..":this.dir=a;this.file="";return}var b=a.lastIndexOf("/"),c=a.lastIndexOf("\\");b<c?(this.dir=f.substr(a,0,c),a=f.substr(a,c+1,null),this.backslash=!0):c<b?(this.dir=f.substr(a,0,b),a=f.substr(a,b+1,null)):this.dir=null;b=a.lastIndexOf(".");-1!=b?(this.ext=f.substr(a,b+1,null),this.file=f.substr(a,0,b)):(this.ext=null,this.file=a)};k.extension=function(a){a=new k(a);return null==
a.ext?"":a.ext};var m=require("fs"),q=function(){};q.buf2ab=function(a){for(var b=new ArrayBuffer(a.length),c=new Uint8Array(b),d=0,e=a.length;d<e;){var h=d++;c[h]=a[h]}return b};var l=function(){};l.loadArrayBuffer=function(a){return new Promise(function(b,c){m.readFile(a,function(a,d){null!=a?c(a):(a=q.buf2ab(d),b(a))})})};l.loadAudioBuffer=function(a,b){return l.loadArrayBuffer(b).then(function(b){return a.decodeAudioData(b).then(function(a){return a})})};var v=function(){};v.getMergedPeaks=function(a,
b){for(var c=a.length/b|0,d=~~(c/10|0)|0,e=[],f=0,h=a.numberOfChannels;f<h;)for(var g=f++,k=a.getChannelData(g),m=0,n=b;m<n;){for(var p=m++,l=~~(p*c)|0,q=~~(l+c),r=k[0],t=k[0];l<q;){var u=k[l];u>t&&(t=u);u<r&&(r=u);l+=d}if(0==g||t>e[2*p])e[2*p]=t;if(0==g||r<e[2*p+1])e[2*p+1]=r}return e};var w=0;module.exports=d;d.allowedFileTypes="flac mp3 ogg opus weba wav".split(" ")})("undefined"!=typeof exports?exports:"undefined"!=typeof window?window:"undefined"!=typeof self?self:this);
